<a href="https://colab.research.google.com/github/Sankar-A06/Machine-Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 1
1.Peform arithemetic operation on NumPy arrays.

In [2]:
import numpy as np
a = np.array([[2,4,6], [8,10,12],[14,16,18]])# ,dtype=np.float64)
b = np.array([[1,2,3],[4,5,6],[7,8,9]])#, dtype=np.float64)
#Elementwise addition
#print(a+b)
print("addition:- ")
print(np.add(a,b))
#ElementWise subtraction
#print(a-b)
print("subtraction:- ")
print(np.subtract(a,b))
#Elementwise multiplication
#print(a*b)
print("multilplication:- ")
print(np.multiply(a,b))
#Elemmentary Division
#print(a/b)
print("Division:- ")
print(np.divide(a,b))
#Elementary power
#print(a**b)
print("power:- ")
print(np.power(a,b))
#Each element  in an array divides its corresponding element in another array and get remainder mod() or remainder() functions
#print(a%b)
print("remainder:- ")
print(np.mod(a,b))
#Elementary division and get corresponding quiotent
#print(a//b)
print("quotient:- ")
print(np.divmod(a,b))
#Each element got a positive value
print("absolute:- ")
print(np.abs(a))
print("absolute:- ")
print(np.abs(b))
#Broadcasting
#arithmetic operations on scalar by broadcasting
print(a+2)

addition:- 
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
subtraction:- 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
multilplication:- 
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]
Division:- 
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
power:- 
[[           2           16          216]
 [        4096       100000      2985984]
 [   105413504   4294967296 198359290368]]
remainder:- 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
quotient:- 
(array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]))
absolute:- 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
absolute:- 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  6  8]
 [10 12 14]
 [16 18 20]]


2.Write a Script to compute the mean and standard deviation of a Numpy Array.

Mean = sum_of_obesrvations/number_of_observations.

standard_deviation=sqrtof(xi-mean)^2/N.

In [ ]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
#function to find mean
def mean(arr):
  return np.mean(arr)
#function to find standard deviation
def st_dev(arr):
  return np.std(arr)
print("Mean ",mean(array))
print("Standard Deviation ",st_dev(array))


Mean  5.5
Standard Deviation  2.8722813232690143


3.Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
#Creating a NumPy array of integers from 10 to 50 with a step size of 5
x = np.arange(10,55,5)
print(x)
#or
print("or")
a=[]
for i in range(10,55,5):
  a.append(i)
print(a)

[10 15 20 25 30 35 40 45 50]
or
[10, 15, 20, 25, 30, 35, 40, 45, 50]


4.Reshape the array into a 2x4 matrix

In [ ]:
x = np.arange(10,50,5)#first it is a 1x8 matrix
print(np.shape(x))
print("1x8 matrix")
print(x)
print("2x4 matrix")
print(x.reshape(2,4))#reshape into 2x4 matrix
print(x.reshape(2,4).shape)

(8,)
1x8 matrix
[10 15 20 25 30 35 40 45]
2x4 matrix
[[10 15 20 25]
 [30 35 40 45]]
(2, 4)


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

i)	Extract the sub-matrix containing the last two rows and first two columns.




In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])# Extract the sub-matrix containing the last two rows and first two columns
print(arr[1:3,0:2])

[[4 5]
 [7 8]]


ii)	Replace all elements greater than 4 with 0.

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])#Replace all elements greater than 4 with 0
print(arr[arr>4])
arr[arr>4]=0
print(arr)

[5 6 7 8 9]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

•	Extract the sub-matrix containing the last two rows and first two columns.

•	Replace all elements greater than 4 with 0.


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])#Extract the sub-matrix containing the last two rows and first two columns
array = arr[1:,:2]
array[array>4]=0#Replace all elements greater than 4 with 0
print(array)


[[4 0]
 [0 0]]


6.Create two 1D arrays:

•	a = np.array([1, 2, 3])

•	b = np.array([4, 5, 6])

•	Perform element-wise addition, multiplication, and division.


In [ ]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
print("Element-wise Addition")
print(a+b)#Element-wise addition
print("Element-wise multiplication")
print(a*b)#Element-wise multiplication
print("Element-wise Division")
print(a/b)#Element-wise Division

Element-wise Addition
[5 7 9]
Element-wise multiplication
[ 4 10 18]
Element-wise Division
[0.25 0.4  0.5 ]


7.Create a random NumPy array of size (4, 4). Compute:

•	Mean of each column.

•	Maximum value of the entire array.

•	Sum of all elements.


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
for i in range(4):
  print("Mean:-",np.mean(arr[:,i:i+1]))#Mean of each column
print("max:- ",np.max(arr))# Maximum value of the entire array.
print("Sum:- ",np.sum(arr))#Sum of all elements


Mean:- 7.0
Mean:- 8.0
Mean:- 9.0
Mean:- 10.0
max:-  16
Sum:-  136


8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and

multiply the result by 2.

In [ ]:
arr = np.array([1,2,3,4])#add 10 to each element and multiply the result by 2.
a = arr+10
print("sum:- ",np.sum(a)*2)

sum:-  100


9.Perform advanced slicing and indexing on a 3D array.

Create a 3D NumPy array arr of shape (3, 4, 5) with random integers

ranging from 1 to 100. Perform the following:

•	Extract the second "layer" (i.e., the second 2D array) in the first

dimension. • Extract the first two rows and the last three columns from

each "layer."

•	Replace all elements divisible by 3 with -1.


In [ ]:
a = np.random.randint(1,101,size=(3,4,5))#Here is the 3D array with shape(3,4,5) with random integers ranging from 1 to 100
#Here  I Extract the second layer (i.e., the second 2D array) in the first dimension.
print(a)
print("Extract the second layer (i.e., the second 2D array) in the first dimension")
print(a[1:2,:,:])
print()
#Extract the first two rows and the last three columns from each layer or first dimension.
print("Here I Extract the first two rows and the last three columns from each layer or first dimension.")
print(a[:,:2,-3:])
print()
a[a%3==0]=-1
print("Replace all elements divisible by 3 with -1")
print(a)# Replace all elements divisible by 3 with -1

[[[ 39  51  21  75  38]
  [ 15  66  96  62  67]
  [ 76  71  44 100  87]
  [ 31  66  69 100  68]]

 [[ 58  49  64  30  86]
  [ 21  34  62  83  83]
  [ 92   9  88  31  70]
  [ 94  83 100  25  35]]

 [[ 87  64  71  80  16]
  [ 81  16  76  70  90]
  [ 15   1  93  43  80]
  [ 59  16  22  74  41]]]
Extract the second layer (i.e., the second 2D array) in the first dimension
[[[ 58  49  64  30  86]
  [ 21  34  62  83  83]
  [ 92   9  88  31  70]
  [ 94  83 100  25  35]]]

Here I Extract the first two rows and the last three columns from each layer or first dimension.
[[[21 75 38]
  [96 62 67]]

 [[64 30 86]
  [62 83 83]]

 [[71 80 16]
  [76 70 90]]]

Replace all elements divisible by 3 with -1
[[[ -1  -1  -1  -1  38]
  [ -1  -1  -1  62  67]
  [ 76  71  44 100  -1]
  [ 31  -1  -1 100  68]]

 [[ 58  49  64  -1  86]
  [ -1  34  62  83  83]
  [ 92  -1  88  31  70]
  [ 94  83 100  25  35]]

 [[ -1  64  71  80  16]
  [ -1  16  76  70  -1]
  [ -1   1  -1  43  80]
  [ 59  16  22  74  41]]]


10.Work with broadcasting and advanced operations in NumPy.

Create a NumPy array arr of shape (3, 3) with random integers

between 1 and 20. Perform the following:

•	Subtract the mean of each row from its respective elements

 (row-wise normalization).

•	Create a new array by squaring all the elements in arr.

•	Find the indices of the top 3 maximum values in the entire array.


In [7]:

arr = np.random.randint(1, 21, size=(3, 3))# Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20.
row1=arr[0:1,:]-np.mean(arr[0:1,:])# Subtract the mean of each row from its respective elements (row-wise normalization).
row2=arr[1:2,:]-np.mean(arr[1:2,:])
row3=arr[2:3,:]-np.mean(arr[2:3,:])
print("original array:-",arr)
print(row1,"\n",row2,"\n",row3)
squared_arr = np.square(arr)# Create a new array by squaring all the elements in arr.
flat_arr = arr.ravel()
sorted_indices = np.argsort(flat_arr)[-3:]
highest_indices = [np.unravel_index(idx, arr.shape) for idx in sorted_indices]
highest_values= [flat_arr[idx] for idx in sorted_indices]
#print("Row-Wise Normalization",normalized_arr)
print("Squared Array",squared_arr)
for value, index in zip(highest_values,highest_indices):
    print("Value:",value, "at Index: ",index)

original array:- [[17  6 14]
 [ 1 19 18]
 [18 19 10]]
[[ 4.66666667 -6.33333333  1.66666667]] 
 [[-11.66666667   6.33333333   5.33333333]] 
 [[ 2.33333333  3.33333333 -5.66666667]]
Squared Array [[289  36 196]
 [  1 361 324]
 [324 361 100]]
Value: 18 at Index:  (2, 0)
Value: 19 at Index:  (1, 1)
Value: 19 at Index:  (2, 1)
