<a href="https://colab.research.google.com/github/Sankar-A06/Machine-Learning/blob/main/Logisitic_regresssion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Logistic Regression Model

*Importing packages*

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Here my input is random numbers of 100 with 5 types
My target is binary variable which is discrete

In [77]:
np.random.seed(42)
X = np.random.rand(100, 5)
y = np.random.randint(0, 2, 100)

In [79]:
X.shape,y.shape

((100, 5), (100,))

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Standardizing is important for logistic regression

In [81]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [83]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)
y_prediction = model.predict(X_test_scaled)

In [84]:
model.score(X_train, y_train)

0.625

In [85]:
model.score(X_test, y_test)

0.5

In [88]:
model.intercept_

array([-0.5161065])

In [90]:
model.coef_

array([[ 0.09727663,  0.01586448, -0.10966115,  0.09803391,  0.00367278]])

In [92]:
accuracy = accuracy_score(y_test, y_prediction)
conf_matrix = confusion_matrix(y_test, y_prediction)
class_report = classification_report(y_test, y_prediction)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [94]:
print("Logistic Regression of targeting binary type")
print("Accuracy: ",accuracy)
print("Confusion Matrix:\n",conf_matrix)
print("Classification Report:\n ",class_report)

Logistic Regression of targeting binary type
Accuracy:  0.5
Confusion Matrix:
 [[10  0]
 [10  0]]
Classification Report:
                precision    recall  f1-score   support

           0       0.50      1.00      0.67        10
           1       0.00      0.00      0.00        10

    accuracy                           0.50        20
   macro avg       0.25      0.50      0.33        20
weighted avg       0.25      0.50      0.33        20

